import PageLayout from "@/components/PageLayout";
import SEO from "@/components/SEO";
import { useLanguage } from "@/hooks/useLanguage";

const EMAIL = "magnifiquedigitalworld@gmail.com";

const EnglishContent = () => (
  <>
    <h1>Privacy Policy</h1>
    <p>Last updated: July 06, 2026</p>
    <p>This Privacy Policy describes Our policies and procedures on the collection, use and disclosure of Your information when You use the Service and tells You about Your privacy rights and how the law protects You.</p>
    <p>We use Your Personal Data to provide and improve the Service. By using the Service, You agree to the collection and use of information in accordance with this Privacy Policy.</p>

    <h2>Interpretation and Definitions</h2>
    <h3>Interpretation</h3>
    <p>The words whose initial letters are capitalized have meanings defined under the following conditions. The following definitions shall have the same meaning regardless of whether they appear in singular or in plural.</p>
    <h3>Definitions</h3>
    <p>For the purposes of this Privacy Policy:</p>
    <ul>
      <li><p><strong>Account</strong> means a unique account created for You to access our Service or parts of our Service.</p></li>
      <li><p><strong>Affiliate</strong> means an entity that controls, is controlled by, or is under common control with a party, where &quot;control&quot; means ownership of 50% or more of the shares, equity interest or other securities entitled to vote for election of directors or other managing authority.</p></li>
      <li><p><strong>Company</strong> (referred to as either &quot;the Company&quot;, &quot;We&quot;, &quot;Us&quot; or &quot;Our&quot; in this Privacy Policy) refers to Magnifique numérique.</p></li>
      <li><p><strong>Cookies</strong> are small files that are placed on Your computer, mobile device or any other device by a website, containing the details of Your browsing history on that website among its many uses.</p></li>
      <li><p><strong>Country</strong> refers to: Ukraine</p></li>
      <li><p><strong>Device</strong> means any device that can access the Service such as a computer, a cell phone or a digital tablet.</p></li>
      <li>
        <p><strong>Personal Data</strong> (or &quot;Personal Information&quot;) is any information that relates to an identified or identifiable individual.</p>
        <p>We use &quot;Personal Data&quot; and &quot;Personal Information&quot; interchangeably unless a law uses a specific term.</p>
      </li>
      <li><p><strong>Service</strong> refers to the Website.</p></li>
      <li><p><strong>Service Provider</strong> means any natural or legal person who processes the data on behalf of the Company. It refers to third-party companies or individuals employed by the Company to facilitate the Service, to provide the Service on behalf of the Company, to perform services related to the Service or to assist the Company in analyzing how the Service is used.</p></li>
      <li><p><strong>Usage Data</strong> refers to data collected automatically, either generated by the use of the Service or from the Service infrastructure itself (for example, the duration of a page visit).</p></li>
      <li><p><strong>Website</strong> refers to Magnifique numérique, accessible from <a href="https://magnifiquedigitalworld.vercel.app/" rel="external nofollow noopener" target="_blank">https://magnifiquedigitalworld.vercel.app/</a>.</p></li>
      <li><p><strong>You</strong> means the individual accessing or using the Service, or the company, or other legal entity on behalf of which such individual is accessing or using the Service, as applicable.</p></li>
    </ul>

    <h2>Collecting and Using Your Personal Data</h2>
    <h3>Types of Data Collected</h3>
    <h4>Personal Data</h4>
    <p>While using Our Service, We may ask You to provide Us with certain personally identifiable information that can be used to contact or identify You. Personally identifiable information may include, but is not limited to:</p>
    <h4>Usage Data</h4>
    <p>Usage Data is collected automatically when using the Service.</p>
    <p>Usage Data may include information such as Your Device's Internet Protocol address (e.g. IP address), browser type, browser version, the pages of our Service that You visit, the time and date of Your visit, the time spent on those pages, unique device identifiers and other diagnostic data.</p>
    <p>When You access the Service by or through a mobile device, We may collect certain information automatically, including, but not limited to, the type of mobile device You use, Your mobile device's unique ID, the IP address of Your mobile device, Your mobile operating system, the type of mobile Internet browser You use, unique device identifiers and other diagnostic data.</p>
    <p>We may also collect information that Your browser sends whenever You visit Our Service or when You access the Service by or through a mobile device.</p>
    <h4>Tracking Technologies and Cookies</h4>
    <p>We use Cookies and similar tracking technologies to track the activity on Our Service and store certain information. Tracking technologies We use include beacons, tags, and scripts to collect and track information and to improve and analyze Our Service. The technologies We use may include:</p>
    <ul>
      <li><strong>Cookies or Browser Cookies.</strong> A cookie is a small file placed on Your Device. You can instruct Your browser to refuse all Cookies or to indicate when a Cookie is being sent. However, if You do not accept Cookies, You may not be able to use some parts of our Service.</li>
      <li><strong>Web Beacons.</strong> Certain sections of our Service and our emails may contain small electronic files known as web beacons (also referred to as clear gifs, pixel tags, and single-pixel gifs) that permit the Company, for example, to count users who have visited those pages or opened an email and for other related website statistics (for example, recording the popularity of a certain section and verifying system and server integrity).</li>
    </ul>
    <p>Cookies can be &quot;Persistent&quot; or &quot;Session&quot; Cookies. Persistent Cookies remain on Your personal computer or mobile device when You go offline, while Session Cookies are deleted as soon as You close Your web browser.</p>
    <p>Where required by law, we use non-essential cookies (such as analytics, advertising, and remarketing cookies) only with Your consent. You can withdraw or change Your consent at any time using Our cookie preferences tool (if available) or through Your browser/device settings. Withdrawing consent does not affect the lawfulness of processing based on consent before its withdrawal.</p>
    <p>We use both Session and Persistent Cookies for the purposes set out below:</p>
    <ul>
      <li>
        <p><strong>Necessary / Essential Cookies</strong></p>
        <p>Type: Session Cookies</p>
        <p>Administered by: Us</p>
        <p>Purpose: These Cookies are essential to provide You with services available through the Website and to enable You to use some of its features. They help to authenticate users and prevent fraudulent use of user accounts. Without these Cookies, the services that You have asked for cannot be provided, and We only use these Cookies to provide You with those services.</p>
      </li>
      <li>
        <p><strong>Cookies Policy / Notice Acceptance Cookies</strong></p>
        <p>Type: Persistent Cookies</p>
        <p>Administered by: Us</p>
        <p>Purpose: These Cookies identify if users have accepted the use of cookies on the Website.</p>
      </li>
      <li>
        <p><strong>Functionality Cookies</strong></p>
        <p>Type: Persistent Cookies</p>
        <p>Administered by: Us</p>
        <p>Purpose: These Cookies allow Us to remember choices You make when You use the Website, such as remembering your login details or language preference. The purpose of these Cookies is to provide You with a more personal experience and to avoid You having to re-enter your preferences every time You use the Website.</p>
      </li>
    </ul>
    <p>For more information about the cookies we use and your choices regarding cookies, please visit our Cookies Policy or the Cookies section of Our Privacy Policy.</p>

    <h3>Use of Your Personal Data</h3>
    <p>The Company may use Personal Data for the following purposes:</p>
    <ul>
      <li><p><strong>To provide and maintain our Service</strong>, including to monitor the usage of our Service.</p></li>
      <li><p><strong>To manage Your Account:</strong> to manage Your registration as a user of the Service. The Personal Data You provide can give You access to different functionalities of the Service that are available to You as a registered user.</p></li>
      <li><p><strong>For the performance of a contract:</strong> the development, compliance and undertaking of the purchase contract for the products, items or services You have purchased or of any other contract with Us through the Service.</p></li>
      <li><p><strong>To contact You:</strong> To contact You by email, telephone calls, SMS, or other equivalent forms of electronic communication, such as a mobile application's push notifications regarding updates or informative communications related to the functionalities, products or contracted services, including the security updates, when necessary or reasonable for their implementation.</p></li>
      <li><p><strong>To provide You</strong> with news, special offers, and general information about other goods, services and events which We offer that are similar to those that you have already purchased or inquired about unless You have opted not to receive such information.</p></li>
      <li><p><strong>To manage Your requests:</strong> To attend and manage Your requests to Us.</p></li>
      <li><p><strong>For business transfers:</strong> We may use Your Personal Data to evaluate or conduct a merger, divestiture, restructuring, reorganization, dissolution, or other sale or transfer of some or all of Our assets, whether as a going concern or as part of bankruptcy, liquidation, or similar proceeding, in which Personal Data held by Us about our Service users is among the assets transferred.</p></li>
      <li><p><strong>For other purposes</strong>: We may use Your information for other purposes, such as data analysis, identifying usage trends, determining the effectiveness of our promotional campaigns and to evaluate and improve our Service, products, services, marketing and your experience.</p></li>
    </ul>
    <p>We may share Your Personal Data in the following situations:</p>
    <ul>
      <li><strong>With Service Providers:</strong> We may share Your Personal Data with Service Providers to monitor and analyze the use of our Service, to contact You.</li>
      <li><strong>For business transfers:</strong> We may share or transfer Your Personal Data in connection with, or during negotiations of, any merger, sale of Company assets, financing, or acquisition of all or a portion of Our business to another company.</li>
      <li><strong>With Affiliates:</strong> We may share Your Personal Data with Our affiliates, in which case we will require those affiliates to honor this Privacy Policy. Affiliates include Our parent company and any other subsidiaries, joint venture partners or other companies that We control or that are under common control with Us.</li>
      <li><strong>With business partners:</strong> We may share Your Personal Data with Our business partners to offer You certain products, services or promotions.</li>
      <li><strong>With other users:</strong> If Our Service offers public areas, when You share Personal Data or otherwise interact in the public areas with other users, such information may be viewed by all users and may be publicly distributed outside.</li>
      <li><strong>With Your consent</strong>: We may disclose Your Personal Data for any other purpose with Your consent.</li>
    </ul>

    <h3>Retention of Your Personal Data</h3>
    <p>The Company will retain Your Personal Data only for as long as is necessary for the purposes set out in this Privacy Policy. We will retain and use Your Personal Data to the extent necessary to comply with our legal obligations (for example, if We are required to retain Your data to comply with applicable laws), resolve disputes, and enforce our legal agreements and policies.</p>
    <p>Where possible, We apply shorter retention periods and/or reduce identifiability by deleting, aggregating, or anonymizing data. Unless otherwise stated, the retention periods below are maximum periods (&quot;up to&quot;) and We may delete or anonymize data sooner when it is no longer needed for the relevant purpose. We apply different retention periods to different categories of Personal Data based on the purpose of processing and legal obligations:</p>
    <ul>
      <li>
        <p>Account Information</p>
        <ul><li>User Accounts: retained for the duration of your account relationship plus up to 24 months after account closure to handle any post-termination issues or resolve disputes.</li></ul>
      </li>
      <li>
        <p>Usage Data</p>
        <ul>
          <li><p>Website analytics data (cookies, IP addresses, device identifiers): up to 24 months from the date of collection, which allows us to analyze trends while respecting privacy principles.</p></li>
          <li><p>Server logs (IP addresses, access times): up to 24 months for security monitoring and troubleshooting purposes.</p></li>
        </ul>
      </li>
    </ul>
    <p>Usage Data is retained in accordance with the retention periods described above, and may be retained longer only where necessary for security, fraud prevention, or legal compliance.</p>
    <p>We may retain Personal Data beyond the periods stated above for different reasons:</p>
    <ul>
      <li>Legal obligation: We are required by law to retain specific data (e.g., financial records for tax authorities).</li>
      <li>Legal claims: Data is necessary to establish, exercise, or defend legal claims.</li>
      <li>Your explicit request: You ask Us to retain specific information.</li>
      <li>Technical limitations: Data exists in backup systems that are scheduled for routine deletion.</li>
    </ul>
    <p>You may request information about how long We will retain Your Personal Data by contacting Us.</p>
    <p>When retention periods expire, We securely delete or anonymize Personal Data according to the following procedures:</p>
    <ul>
      <li>Deletion: Personal Data is removed from Our systems and no longer actively processed.</li>
      <li>Backup retention: Residual copies may remain in encrypted backups for a limited period consistent with our backup retention schedule and are not restored except where necessary for security, disaster recovery, or legal compliance.</li>
      <li>Anonymization: In some cases, We convert Personal Data into anonymous statistical data that cannot be linked back to You. This anonymized data may be retained indefinitely for research and analytics.</li>
    </ul>

    <h3>Transfer of Your Personal Data</h3>
    <p>Your information, including Personal Data, is processed at the Company's operating offices and in any other places where the parties involved in the processing are located. It means that this information may be transferred to — and maintained on — computers located outside of Your state, province, country or other governmental jurisdiction where the data protection laws may differ from those from Your jurisdiction.</p>
    <p>Where required by applicable law, We will ensure that international transfers of Your Personal Data are subject to appropriate safeguards and supplementary measures where appropriate. The Company will take all steps reasonably necessary to ensure that Your data is treated securely and in accordance with this Privacy Policy and no transfer of Your Personal Data will take place to an organization or a country unless there are adequate controls in place including the security of Your data and other personal information.</p>

    <h3>Delete Your Personal Data</h3>
    <p>You have the right to delete or request that We assist in deleting the Personal Data that We have collected about You.</p>
    <p>Our Service may give You the ability to delete certain information about You from within the Service.</p>
    <p>You may update, amend, or delete Your information at any time by signing in to Your Account, if you have one, and visiting the account settings section that allows you to manage Your personal information. You may also contact Us to request access to, correct, or delete any Personal Data that You have provided to Us.</p>
    <p>Please note, however, that We may need to retain certain information when we have a legal obligation or lawful basis to do so.</p>

    <h3>Disclosure of Your Personal Data</h3>
    <h4>Business Transactions</h4>
    <p>If the Company is involved in a merger, acquisition or asset sale, Your Personal Data may be transferred. We will provide notice before Your Personal Data is transferred and becomes subject to a different Privacy Policy.</p>
    <h4>Law enforcement</h4>
    <p>Under certain circumstances, the Company may be required to disclose Your Personal Data if required to do so by law or in response to valid requests by public authorities (e.g. a court or a government agency).</p>
    <h4>Other legal requirements</h4>
    <p>The Company may disclose Your Personal Data in the good faith belief that such action is necessary to:</p>
    <ul>
      <li>Comply with a legal obligation</li>
      <li>Protect and defend the rights or property of the Company</li>
      <li>Prevent or investigate possible wrongdoing in connection with the Service</li>
      <li>Protect the personal safety of Users of the Service or the public</li>
      <li>Protect against legal liability</li>
    </ul>

    <h3>Security of Your Personal Data</h3>
    <p>The security of Your Personal Data is important to Us, but remember that no method of transmission over the Internet, or method of electronic storage is 100% secure. While We strive to use commercially reasonable means to protect Your Personal Data, We cannot guarantee its absolute security.</p>

    <h2>Children's Privacy</h2>
    <p>Our Service does not address anyone under the age of 16. We do not knowingly collect personally identifiable information from anyone under the age of 16. If You are a parent or guardian and You are aware that Your child has provided Us with Personal Data, please contact Us. If We become aware that We have collected Personal Data from anyone under the age of 16 without verification of parental consent, We take steps to remove that information from Our servers.</p>
    <p>If We need to rely on consent as a legal basis for processing Your information and Your country requires consent from a parent, We may require Your parent's consent before We collect and use that information.</p>

    <h2>Links to Other Websites</h2>
    <p>Our Service may contain links to other websites that are not operated by Us. If You click on a third party link, You will be directed to that third party's site. We strongly advise You to review the Privacy Policy of every site You visit.</p>
    <p>We have no control over and assume no responsibility for the content, privacy policies or practices of any third party sites or services.</p>

    <h2>Changes to this Privacy Policy</h2>
    <p>We may update Our Privacy Policy from time to time. We will notify You of any changes by posting the new Privacy Policy on this page.</p>
    <p>We will let You know via email and/or a prominent notice on Our Service, prior to the change becoming effective and update the &quot;Last updated&quot; date at the top of this Privacy Policy.</p>
    <p>You are advised to review this Privacy Policy periodically for any changes. Changes to this Privacy Policy are effective when they are posted on this page.</p>

    <h2>Contact Us</h2>
    <p>If you have any questions about this Privacy Policy, You can contact us:</p>
    <ul>
      <li>By email: <a href={`mailto:${EMAIL}`}>{EMAIL}</a></li>
    </ul>
  </>
);

const UkrainianContent = () => (
  <>
    <h1>Політика конфіденційності</h1>
    <p>Останнє оновлення: 06 липня 2026 року</p>
    <p>Ця Політика конфіденційності описує Наші правила та процедури щодо збору, використання та розкриття Вашої інформації під час використання Вами Сервісу, а також інформує Вас про Ваші права на конфіденційність і про те, як закон захищає Вас.</p>
    <p>Ми використовуємо Ваші Персональні дані для надання та вдосконалення Сервісу. Використовуючи Сервіс, Ви погоджуєтеся зі збором та використанням інформації відповідно до цієї Політики конфіденційності.</p>

    <h2>Тлумачення та визначення</h2>
    <h3>Тлумачення</h3>
    <p>Слова, перші літери яких пишуться з великої літери, мають значення, визначені за наведених нижче умов. Наступні визначення мають однакове значення незалежно від того, вживаються вони в однині чи множині.</p>
    <h3>Визначення</h3>
    <p>Для цілей цієї Політики конфіденційності:</p>
    <ul>
      <li><p><strong>Обліковий запис</strong> означає унікальний обліковий запис, створений для Вас з метою доступу до нашого Сервісу або його частин.</p></li>
      <li><p><strong>Афілійована особа</strong> означає юридичну особу, яка контролює, контролюється або перебуває під спільним контролем зі стороною, де «контроль» означає володіння 50% або більше акцій, часток або інших цінних паперів, що дають право голосу під час обрання директорів або іншого керівного органу.</p></li>
      <li><p><strong>Компанія</strong> (згадується як «Компанія», «Ми», «Нас» або «Наш» у цій Політиці конфіденційності) означає Magnifique numérique.</p></li>
      <li><p><strong>Файли cookie</strong> — це невеликі файли, які розміщуються на Вашому комп'ютері, мобільному пристрої чи будь-якому іншому пристрої вебсайтом і містять, серед іншого, деталі Вашої історії перегляду цього вебсайту.</p></li>
      <li><p><strong>Країна</strong> означає: Україна</p></li>
      <li><p><strong>Пристрій</strong> означає будь-який пристрій, що має доступ до Сервісу, наприклад комп'ютер, мобільний телефон або цифровий планшет.</p></li>
      <li>
        <p><strong>Персональні дані</strong> (або «Персональна інформація») — це будь-яка інформація, що стосується ідентифікованої або такої, що може бути ідентифікована, особи.</p>
        <p>Ми використовуємо терміни «Персональні дані» та «Персональна інформація» як взаємозамінні, якщо законом не передбачено інший конкретний термін.</p>
      </li>
      <li><p><strong>Сервіс</strong> означає Вебсайт.</p></li>
      <li><p><strong>Постачальник послуг</strong> означає будь-яку фізичну або юридичну особу, яка обробляє дані від імені Компанії. Це стосується сторонніх компаній або осіб, найнятих Компанією для сприяння роботі Сервісу, надання Сервісу від імені Компанії, виконання послуг, пов'язаних із Сервісом, або допомоги Компанії в аналізі використання Сервісу.</p></li>
      <li><p><strong>Дані про використання</strong> означають дані, які збираються автоматично, згенеровані використанням Сервісу або самою інфраструктурою Сервісу (наприклад, тривалість відвідування сторінки).</p></li>
      <li><p><strong>Вебсайт</strong> означає Magnifique numérique, доступний за адресою <a href="https://magnifiquedigitalworld.vercel.app/" rel="external nofollow noopener" target="_blank">https://magnifiquedigitalworld.vercel.app/</a>.</p></li>
      <li><p><strong>Ви</strong> означає фізичну особу, яка отримує доступ до Сервісу або використовує його, або компанію чи іншу юридичну особу, від імені якої така фізична особа отримує доступ до Сервісу чи використовує його, залежно від обставин.</p></li>
    </ul>

    <h2>Збір і використання Ваших Персональних даних</h2>
    <h3>Типи даних, що збираються</h3>
    <h4>Персональні дані</h4>
    <p>Під час користування Нашим Сервісом Ми можемо попросити Вас надати певну персональну ідентифікаційну інформацію, яку можна використати для зв'язку з Вами або Вашої ідентифікації. Персональна ідентифікаційна інформація може включати, зокрема:</p>
    <h4>Дані про використання</h4>
    <p>Дані про використання збираються автоматично під час користування Сервісом.</p>
    <p>Дані про використання можуть містити таку інформацію, як IP-адреса Вашого Пристрою (наприклад, IP-адреса), тип браузера, версія браузера, сторінки нашого Сервісу, які Ви відвідуєте, час і дата Вашого відвідування, час, проведений на цих сторінках, унікальні ідентифікатори пристроїв та інші діагностичні дані.</p>
    <p>Коли Ви отримуєте доступ до Сервісу через мобільний пристрій, Ми можемо автоматично збирати певну інформацію, включаючи, зокрема, тип мобільного пристрою, який Ви використовуєте, його унікальний ідентифікатор, IP-адресу Вашого мобільного пристрою, Вашу мобільну операційну систему, тип мобільного інтернет-браузера, унікальні ідентифікатори пристрою та інші діагностичні дані.</p>
    <p>Ми також можемо збирати інформацію, яку надсилає Ваш браузер щоразу, коли Ви відвідуєте наш Сервіс або отримуєте до нього доступ через мобільний пристрій.</p>
    <h4>Технології відстеження та файли cookie</h4>
    <p>Ми використовуємо файли cookie та подібні технології відстеження для відстеження активності на нашому Сервісі та зберігання певної інформації. Технології відстеження, які Ми використовуємо, включають маячки, теги та сценарії для збору й відстеження інформації, а також для покращення й аналізу нашого Сервісу. Технології, які Ми використовуємо, можуть включати:</p>
    <ul>
      <li><strong>Файли cookie або файли cookie браузера.</strong> Cookie — це невеликий файл, розміщений на Вашому Пристрої. Ви можете налаштувати свій браузер так, щоб він відхиляв усі cookie або повідомляв, коли надсилається cookie. Однак, якщо Ви не приймаєте cookie, Ви можете не мати можливості користуватися деякими частинами нашого Сервісу.</li>
      <li><strong>Вебмаячки.</strong> Певні розділи нашого Сервісу та наших електронних листів можуть містити невеликі електронні файли, відомі як вебмаячки (також звані clear gifs, піксельні теги та однопіксельні gifs), що дозволяють Компанії, наприклад, підраховувати користувачів, які відвідали ці сторінки або відкрили електронний лист, а також збирати іншу статистику вебсайту (наприклад, фіксувати популярність певного розділу та перевіряти цілісність системи і сервера).</li>
    </ul>
    <p>Файли cookie можуть бути «постійними» або «сеансовими». Постійні cookie залишаються на Вашому персональному комп'ютері чи мобільному пристрої, коли Ви переходите в офлайн, тоді як сеансові cookie видаляються одразу після закриття вебпереглядача.</p>
    <p>Там, де це вимагається законом, ми використовуємо неосновні cookie (наприклад, аналітичні, рекламні та ремаркетингові) лише за Вашою згодою. Ви можете відкликати або змінити свою згоду в будь-який час за допомогою нашого інструменту налаштування cookie (якщо доступний) або через налаштування Вашого браузера/пристрою. Відкликання згоди не впливає на законність обробки, що ґрунтується на згоді до її відкликання.</p>
    <p>Ми використовуємо як сеансові, так і постійні cookie для цілей, викладених нижче:</p>
    <ul>
      <li>
        <p><strong>Необхідні / основні cookie</strong></p>
        <p>Тип: сеансові cookie</p>
        <p>Керуються: Нами</p>
        <p>Призначення: ці cookie є важливими для надання Вам послуг, доступних через Вебсайт, і забезпечення можливості використання деяких його функцій. Вони допомагають автентифікувати користувачів і запобігати шахрайському використанню облікових записів. Без цих cookie послуги, які Ви запросили, не можуть бути надані, і Ми використовуємо ці cookie лише для надання Вам цих послуг.</p>
      </li>
      <li>
        <p><strong>Cookie політики / прийняття повідомлення про cookie</strong></p>
        <p>Тип: постійні cookie</p>
        <p>Керуються: Нами</p>
        <p>Призначення: ці cookie ідентифікують, чи прийняли користувачі використання cookie на Вебсайті.</p>
      </li>
      <li>
        <p><strong>Функціональні cookie</strong></p>
        <p>Тип: постійні cookie</p>
        <p>Керуються: Нами</p>
        <p>Призначення: ці cookie дозволяють Нам запам'ятовувати вибір, який Ви робите під час використання Вебсайту, наприклад Ваші дані для входу або мовні налаштування. Мета цих cookie — забезпечити Вам більш персоналізований досвід і уникнути необхідності повторно вводити свої налаштування щоразу під час використання Вебсайту.</p>
      </li>
    </ul>
    <p>Для отримання додаткової інформації про cookie, які ми використовуємо, і Ваш вибір щодо cookie, будь ласка, відвідайте нашу Політику щодо cookie або розділ Cookie нашої Політики конфіденційності.</p>

    <h3>Використання Ваших Персональних даних</h3>
    <p>Компанія може використовувати Персональні дані для таких цілей:</p>
    <ul>
      <li><p><strong>Для надання та підтримки нашого Сервісу</strong>, зокрема для моніторингу використання нашого Сервісу.</p></li>
      <li><p><strong>Для управління Вашим Обліковим записом:</strong> для управління Вашою реєстрацією як користувача Сервісу. Персональні дані, які Ви надаєте, можуть надати Вам доступ до різних функцій Сервісу, доступних Вам як зареєстрованому користувачу.</p></li>
      <li><p><strong>Для виконання договору:</strong> розробка, дотримання та виконання договору купівлі продуктів, товарів чи послуг, які Ви придбали, або будь-якого іншого договору з Нами через Сервіс.</p></li>
      <li><p><strong>Для зв'язку з Вами:</strong> для зв'язку з Вами електронною поштою, телефоном, SMS або іншими рівнозначними формами електронної комунікації, наприклад push-повідомленнями мобільного застосунку щодо оновлень чи інформаційних повідомлень, пов'язаних із функціями, продуктами або замовленими послугами, включно з оновленнями безпеки, коли це необхідно чи доцільно для їх реалізації.</p></li>
      <li><p><strong>Для надання Вам</strong> новин, спеціальних пропозицій і загальної інформації про інші товари, послуги та події, які Ми пропонуємо і які подібні до тих, які Ви вже придбали або про які запитували, якщо Ви не відмовилися від отримання такої інформації.</p></li>
      <li><p><strong>Для управління Вашими запитами:</strong> для розгляду й обробки Ваших запитів до Нас.</p></li>
      <li><p><strong>Для передачі бізнесу:</strong> Ми можемо використовувати Ваші Персональні дані для оцінки або здійснення злиття, продажу активів, реструктуризації, реорганізації, ліквідації чи іншого продажу або передачі частини чи всіх Наших активів, як під час звичайної діяльності, так і в межах банкрутства, ліквідації чи подібних процедур, у яких Персональні дані користувачів Сервісу входять до переданих активів.</p></li>
      <li><p><strong>Для інших цілей</strong>: Ми можемо використовувати Вашу інформацію для інших цілей, таких як аналіз даних, визначення тенденцій використання, оцінка ефективності наших рекламних кампаній, а також для оцінки й покращення нашого Сервісу, продуктів, послуг, маркетингу та Вашого досвіду.</p></li>
    </ul>
    <p>Ми можемо ділитися Вашими Персональними даними у наступних ситуаціях:</p>
    <ul>
      <li><strong>З Постачальниками послуг:</strong> Ми можемо ділитися Вашими Персональними даними з Постачальниками послуг для моніторингу та аналізу використання нашого Сервісу, а також для зв'язку з Вами.</li>
      <li><strong>Для передачі бізнесу:</strong> Ми можемо передавати Ваші Персональні дані у зв'язку з будь-яким злиттям, продажем активів Компанії, фінансуванням чи придбанням усього або частини нашого бізнесу іншою компанією.</li>
      <li><strong>З Афілійованими особами:</strong> Ми можемо ділитися Вашими Персональними даними з нашими афілійованими особами, від яких ми вимагатимемо дотримання цієї Політики конфіденційності. До афілійованих осіб належать наша материнська компанія та будь-які інші дочірні компанії, партнери зі спільних підприємств чи інші компанії, які Ми контролюємо або які перебувають під спільним контролем з Нами.</li>
      <li><strong>З діловими партнерами:</strong> Ми можемо ділитися Вашими Персональними даними з нашими діловими партнерами, щоб пропонувати Вам певні продукти, послуги або акції.</li>
      <li><strong>З іншими користувачами:</strong> якщо наш Сервіс пропонує публічні зони, коли Ви ділитеся Персональними даними або іншим чином взаємодієте в публічних зонах з іншими користувачами, така інформація може бути переглянута всіма користувачами і публічно поширена за межами.</li>
      <li><strong>За Вашою згодою</strong>: Ми можемо розкривати Ваші Персональні дані для будь-якої іншої мети за Вашою згодою.</li>
    </ul>

    <h3>Зберігання Ваших Персональних даних</h3>
    <p>Компанія зберігатиме Ваші Персональні дані лише протягом часу, необхідного для цілей, зазначених у цій Політиці конфіденційності. Ми зберігатимемо та використовуватимемо Ваші Персональні дані в обсязі, необхідному для дотримання наших юридичних зобов'язань (наприклад, якщо Ми зобов'язані зберігати Ваші дані відповідно до чинного законодавства), вирішення спорів і виконання наших юридичних угод та політик.</p>
    <p>Де це можливо, Ми застосовуємо коротші періоди зберігання та/або зменшуємо ідентифікованість шляхом видалення, агрегування або анонімізації даних. Якщо не зазначено інше, зазначені нижче періоди зберігання є максимальними («до») і Ми можемо видаляти або анонімізувати дані раніше, коли вони більше не потрібні для відповідної мети. Ми застосовуємо різні періоди зберігання для різних категорій Персональних даних залежно від мети обробки та юридичних зобов'язань:</p>
    <ul>
      <li>
        <p>Інформація облікового запису</p>
        <ul><li>Облікові записи користувачів: зберігаються протягом усього періоду відносин за обліковим записом плюс до 24 місяців після його закриття для розгляду можливих післядоговірних питань або вирішення спорів.</li></ul>
      </li>
      <li>
        <p>Дані про використання</p>
        <ul>
          <li><p>Аналітичні дані вебсайту (cookie, IP-адреси, ідентифікатори пристроїв): до 24 місяців з дати збору, що дозволяє нам аналізувати тенденції, дотримуючись принципів конфіденційності.</p></li>
          <li><p>Журнали серверів (IP-адреси, час доступу): до 24 місяців для цілей моніторингу безпеки та усунення несправностей.</p></li>
        </ul>
      </li>
    </ul>
    <p>Дані про використання зберігаються відповідно до наведених вище періодів і можуть зберігатися довше лише у разі потреби для цілей безпеки, запобігання шахрайству або дотримання законодавства.</p>
    <p>Ми можемо зберігати Персональні дані понад вказані вище періоди з різних причин:</p>
    <ul>
      <li>Юридичне зобов'язання: закон вимагає від нас зберігати певні дані (наприклад, фінансові записи для податкових органів).</li>
      <li>Юридичні претензії: дані необхідні для встановлення, здійснення або захисту юридичних претензій.</li>
      <li>Ваш явний запит: Ви просите Нас зберегти певну інформацію.</li>
      <li>Технічні обмеження: дані існують у резервних системах, які підлягають плановому видаленню.</li>
    </ul>
    <p>Ви можете запитати інформацію про те, як довго Ми зберігатимемо Ваші Персональні дані, зв'язавшись із Нами.</p>
    <p>Після закінчення періодів зберігання Ми безпечно видаляємо або анонімізуємо Персональні дані відповідно до таких процедур:</p>
    <ul>
      <li>Видалення: Персональні дані видаляються з наших систем і більше не обробляються активно.</li>
      <li>Зберігання резервних копій: залишкові копії можуть залишатися у зашифрованих резервних копіях протягом обмеженого періоду відповідно до графіка зберігання резервних копій і не відновлюються, окрім випадків, коли це необхідно для безпеки, аварійного відновлення або дотримання законодавства.</li>
      <li>Анонімізація: у деяких випадках Ми перетворюємо Персональні дані на анонімні статистичні дані, які неможливо пов'язати з Вами. Ці анонімізовані дані можуть зберігатися необмежений час для досліджень і аналітики.</li>
    </ul>

    <h3>Передача Ваших Персональних даних</h3>
    <p>Ваша інформація, включаючи Персональні дані, обробляється в операційних офісах Компанії та в будь-яких інших місцях, де знаходяться сторони, задіяні в обробці. Це означає, що ця інформація може передаватися та зберігатися на комп'ютерах, розташованих за межами Вашої держави, провінції, країни або іншої юрисдикції, де закони про захист даних можуть відрізнятися від законів Вашої юрисдикції.</p>
    <p>Де це вимагається чинним законодавством, Ми забезпечимо, щоб міжнародні передачі Ваших Персональних даних здійснювалися з відповідними гарантіями та додатковими заходами, де це доречно. Компанія вживатиме всіх заходів, необхідних для забезпечення безпечного поводження з Вашими даними відповідно до цієї Політики конфіденційності, і жодна передача Ваших Персональних даних не відбудеться до організації чи країни без належного контролю, зокрема безпеки Ваших даних та іншої персональної інформації.</p>

    <h3>Видалення Ваших Персональних даних</h3>
    <p>Ви маєте право видалити або попросити Нас допомогти Вам видалити Персональні дані, які Ми зібрали про Вас.</p>
    <p>Наш Сервіс може надати Вам можливість видалити певну інформацію про Вас безпосередньо в Сервісі.</p>
    <p>Ви можете оновлювати, змінювати або видаляти Вашу інформацію в будь-який час, увійшовши до Вашого Облікового запису, якщо він у Вас є, і відвідавши розділ налаштувань, який дозволяє керувати Вашою персональною інформацією. Ви також можете зв'язатися з Нами, щоб запросити доступ до, виправлення або видалення будь-яких Персональних даних, які Ви нам надали.</p>
    <p>Зверніть увагу, однак, що Ми можемо бути змушені зберегти певну інформацію, коли у нас є юридичне зобов'язання або законна підстава для цього.</p>

    <h3>Розкриття Ваших Персональних даних</h3>
    <h4>Ділові операції</h4>
    <p>Якщо Компанія бере участь у злитті, придбанні або продажу активів, Ваші Персональні дані можуть бути передані. Ми повідомимо Вас до передачі Ваших Персональних даних і до того, як вони стануть предметом іншої Політики конфіденційності.</p>
    <h4>Правоохоронні органи</h4>
    <p>За певних обставин Компанія може бути зобов'язана розкривати Ваші Персональні дані, якщо цього вимагає закон або у відповідь на обґрунтовані запити державних органів (наприклад, суду чи державної установи).</p>
    <h4>Інші юридичні вимоги</h4>
    <p>Компанія може розкривати Ваші Персональні дані, добросовісно вважаючи, що така дія необхідна для:</p>
    <ul>
      <li>Дотримання юридичного зобов'язання</li>
      <li>Захисту прав або власності Компанії</li>
      <li>Запобігання або розслідування можливих порушень у зв'язку із Сервісом</li>
      <li>Захисту особистої безпеки користувачів Сервісу або громадськості</li>
      <li>Захисту від юридичної відповідальності</li>
    </ul>

    <h3>Безпека Ваших Персональних даних</h3>
    <p>Безпека Ваших Персональних даних важлива для Нас, але пам'ятайте, що жоден метод передачі через Інтернет або метод електронного зберігання не є на 100% безпечним. Хоча Ми прагнемо використовувати комерційно прийнятні засоби для захисту Ваших Персональних даних, Ми не можемо гарантувати їх абсолютну безпеку.</p>

    <h2>Конфіденційність дітей</h2>
    <p>Наш Сервіс не адресований особам молодшим за 16 років. Ми свідомо не збираємо персональну ідентифікаційну інформацію від осіб молодших за 16 років. Якщо Ви батько чи опікун і Вам відомо, що Ваша дитина надала Нам Персональні дані, будь ласка, зв'яжіться з Нами. Якщо Ми дізнаємося, що зібрали Персональні дані від осіб молодших за 16 років без підтвердження згоди батьків, Ми вживемо заходів для видалення цієї інформації з наших серверів.</p>
    <p>Якщо Ми маємо покладатися на згоду як на правову підставу для обробки Вашої інформації, і Ваша країна вимагає згоди від одного з батьків, Ми можемо вимагати згоду Вашого батька/матері до збору та використання такої інформації.</p>

    <h2>Посилання на інші вебсайти</h2>
    <p>Наш Сервіс може містити посилання на інші вебсайти, які не керуються Нами. Якщо Ви натиснете на посилання третьої сторони, Вас буде направлено на сайт цієї третьої сторони. Ми наполегливо радимо Вам ознайомитися з Політикою конфіденційності кожного сайту, який Ви відвідуєте.</p>
    <p>Ми не контролюємо і не несемо відповідальності за зміст, політику конфіденційності або практики будь-яких сторонніх сайтів чи сервісів.</p>

    <h2>Зміни до цієї Політики конфіденційності</h2>
    <p>Ми можемо періодично оновлювати нашу Політику конфіденційності. Ми повідомимо Вас про будь-які зміни, розмістивши нову Політику конфіденційності на цій сторінці.</p>
    <p>Ми повідомимо Вас електронною поштою та/або через помітне повідомлення в нашому Сервісі до набуття чинності змінами та оновимо дату «Останнє оновлення» вгорі цієї Політики конфіденційності.</p>
    <p>Радимо Вам періодично переглядати цю Політику конфіденційності на предмет змін. Зміни до цієї Політики конфіденційності набувають чинності з моменту їх публікації на цій сторінці.</p>

    <h2>Зв'яжіться з нами</h2>
    <p>Якщо у Вас є запитання щодо цієї Політики конфіденційності, Ви можете зв'язатися з нами:</p>
    <ul>
      <li>Електронною поштою: <a href={`mailto:${EMAIL}`}>{EMAIL}</a></li>
    </ul>
  </>
);

const PrivacyPolicy = () => {
  const { language } = useLanguage();
  const isEn = language === "en";

  return (
    <PageLayout>
      <SEO
        title={
          isEn
            ? "Privacy Policy — Magnifique numérique"
            : "Політика конфіденційності — Magnifique numérique"
        }
        description={
          isEn
            ? "Privacy Policy for Magnifique numérique: how we collect, use, and protect your personal data."
            : "Політика конфіденційності Magnifique numérique: як ми збираємо, використовуємо та захищаємо ваші персональні дані."
        }
        path="/privacy-policy"
      />
      <article
        className="
          max-w-3xl mx-auto
          text-foreground
          [&_h1]:text-4xl [&_h1]:font-bold [&_h1]:mt-2 [&_h1]:mb-6
          [&_h2]:text-2xl [&_h2]:font-semibold [&_h2]:mt-10 [&_h2]:mb-4 [&_h2]:text-foreground
          [&_h3]:text-xl [&_h3]:font-semibold [&_h3]:mt-8 [&_h3]:mb-3 [&_h3]:text-foreground
          [&_h4]:text-lg [&_h4]:font-semibold [&_h4]:mt-6 [&_h4]:mb-2 [&_h4]:text-foreground
          [&_p]:my-3 [&_p]:leading-relaxed [&_p]:text-muted-foreground
          [&_ul]:list-disc [&_ul]:pl-6 [&_ul]:my-3 [&_ul]:space-y-2 [&_ul]:text-muted-foreground
          [&_li]:leading-relaxed
          [&_a]:text-primary [&_a]:hover:underline
          [&_strong]:text-foreground
        "
      >
        {isEn ? <EnglishContent /> : <UkrainianContent />}
      </article>
    </PageLayout>
  );
};

export default PrivacyPolicy;
